### ISSUE TITLE
Error when plotting on Windows: `AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'`

### ISSUE THREAD

**Issue by RobertoRoos** [DEMCON/libstored#41]
I get an error trying to open a plot with `libstored.gui`:

```
C:\Users\Name\project\venv\Scripts\python.exe -m libstored.gui -p 55556
Traceback (most recent call last):
  File "C:\Users\Name\project\venv\lib\site-packages\libstored\gui\__main__.py", line 431, in setData
    self.addPlot(o)
  File "C:\Users\Name\project\venv\lib\site-packages\libstored\gui\__main__.py", line 442, in addPlot
    Plotter.add(o)
  File "C:\Users\Name\project\venv\lib\site-packages\libstored\gui\__main__.py", line 133, in add
    cls.instance()._add(o)
  File "C:\Users\Name\project\venv\lib\site-packages\libstored\gui\__main__.py", line 143, in _add
    self._fig, self._ax = plt.subplots()
  File "C:\Users\Name\project\venv\lib\site-packages\matplotlib\pyplot.py", line 1430, in subplots
    fig = figure(**fig_kw)
  File "C:\Users\Name\project\venv\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Name\project\venv\lib\site-packages\matplotlib\pyplot.py", line 771, in figure
    manager = new_figure_manager(
  File "C:\Users\Name\project\venv\lib\site-packages\matplotlib\pyplot.py", line 346, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "C:\Users\Name\project\venv\lib\site-packages\matplotlib\pyplot.py", line 336, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod()) and
  File "C:\Users\Name\project\venv\lib\site-packages\matplotlib\pyplot.py", line 206, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "C:\Users\Name\project\venv\lib\site-packages\matplotlib\pyplot.py", line 266, in switch_backend
    canvas_class = backend_mod.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'. Did you mean: 'FigureCanvasAgg'?

```

**Comment by jhrutgers** [comment]
I cannot reproduce it. Could this be this issue? https://github.com/matplotlib/matplotlib/issues/23911

**Comment by RobertoRoos** [comment]
I can't reproduce it either with libstored v1.5.0. Checking/unchecking plots now also works reliable it seems. Will close.
