### ISSUE TITLE
`ImportError: cannot import name 'gui_qrc' from 'libstored.gui'`

### ISSUE THREAD

**Issue by RobertoRoos** [DEMCON/libstored#52]
I get the following when trying to run the libstored GUI on Windows 10:

> C:\project\dist\venv_win\Scripts\python.exe -m libstored.gui -vvv 
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\project\extern\libstored\python\libstored\gui\__main__.py", line 26, in <module>
>     from . import gui_qrc
> ImportError: cannot import name 'gui_qrc' from 'libstored.gui' (C:\project\extern\libstored\python\libstored\gui\__init__.py)

This is libstored version 1.4.0. Reproduced with:

```
> venv\Scripts\Activate.ps1
(venv) > pip install -r extern\libstored\dist\common\requirements.txt
(venv) > pip install extern\libstored
(venv) > python -m libstored.gui [-vvv]
```

Then I also got the same error when running on Ubuntu in WSL (version 1), in the same folder but a different venv.
I seemed to able to fix it in WSL by running:

```
dist/venv/lib/python3.10/site-packages/PySide6/Qt/libexec/rcc -g python extern/libstored/python/libstored/gui/gui_qrc.py.qrc > dist/venv/lib/python3.10/site-packages/libstored/gui/gui_qrc.py
```

**Comment by RobertoRoos** [comment]
My bad: I forgot the `pip install ...` alone is not enough.
On top of that I was confused and I was trying to share the same build directory between Windows and Linux.

I got libstored to work on Windows (without needing MinGW or GCC) with:

```
(venv) > pip uninstall libstored
(venv) > cd extern\libstored\dist\win32
(venv) > mkdir build && cd build
(venv) > cmake ..\..\.. -DCMAKE_MODULE_PATH="C:/project/extern/libstored/dist/common/" -DCMAKE_INSTALL_PREFIX=deploy -Wno-dev
(venv) > pip install extern\libstored\python
```
